# Generated by Django 4.2.3 on 2023-07-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_modelservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelService',
        ),
    ]
