# Generated by Django 4.2.3 on 2023-07-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_customerservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='img1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='img2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='img3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
