# Generated by Django 4.2.3 on 2023-07-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0006_alter_customerservice_img1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketService',
        ),
    ]
