# Generated by Django 4.2.3 on 2023-07-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0013_intelligenceservice_code_alter_archiveservice_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveservice',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='archiveservice',
            name='image2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='archiveservice',
            name='code',
            field=models.CharField(default='G66815', max_length=100),
        ),
        migrations.AlterField(
            model_name='intelligenceservice',
            name='code',
            field=models.CharField(default='G7351', max_length=100),
        ),
    ]
