# Generated by Django 4.2.3 on 2023-12-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0014_archiveservice_image_archiveservice_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveservice',
            name='code',
            field=models.CharField(default='E7239', max_length=100),
        ),
        migrations.AlterField(
            model_name='intelligenceservice',
            name='code',
            field=models.CharField(default='G55525', max_length=100),
        ),
    ]
