# Generated by Django 4.2.3 on 2023-12-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0016_alter_archiveservice_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOnur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.CharField(max_length=30)),
                ('email', models.TextField()),
                ('kutu', models.TextField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='TicketService',
            new_name='TicketIpek',
        ),
        migrations.AlterField(
            model_name='archiveservice',
            name='code',
            field=models.CharField(default='B44645', max_length=100),
        ),
        migrations.AlterField(
            model_name='intelligenceservice',
            name='code',
            field=models.CharField(default='D37119', max_length=100),
        ),
    ]
