# Generated by Django 4.2.3 on 2023-12-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0017_ticketonur_rename_ticketservice_ticketipek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveservice',
            name='code',
            field=models.CharField(default='C16298', max_length=100),
        ),
        migrations.AlterField(
            model_name='intelligenceservice',
            name='code',
            field=models.CharField(default='C82894', max_length=100),
        ),
    ]
